version: 2
jobs:
  build:
    docker:
      - image: alpine:3.12.0 
    working_directory: /tmp
    steps:
      - run: mkdir -p /tmp/workspace
      - run: echo 'This is artifact' >> /tmp/workspace/artifact.txt
      - run: cat /tmp/workspace/artifact.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - artifact.txt
  deploy:
    docker:
      - image: alpine:3.12.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/artifact.txt

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
